### ISSUE TITLE
Fix event handler error

### ISSUE THREAD

**Issue by lolux** [waltzio/waltz#223]
I'm trying to set up a site config for Internet Archive using the following .json.

```
{
    "*://archive.org/*": {
        "name": "Internet Archive",
        "logout": {
            "cookies": ["PHPSESSID", "logged-in-sig", "logged-in-user"]
        },
        "login": {
            "urls": ["https://archive.org/account/login.php"],
            "formURL": "https://archive.org/account/login.php",
            "formOnly": true,
            "method": "POST",
            "usernameField": "username",
            "passwordField": "password",
            "hasHiddenInputs": true,
            "submitButton": "input#submit",
            "check": "a:contains('log out')"
        }
    }
}
```

Log in attempts fail and return an [event handler error](https://www.dropbox.com/s/ldlwr6fi967sekc/Screenshot%202013-12-29%2000.52.38.jpg) in the console.

Since I've seen this same error message on several other sites for which I'm trying to get site configs working, I'm wondering whether there is an underlying issue or whether I'm making the same mistake on many site configs.

Other weird errors I'm getting from testing this .json include:
- if you set `formOnly` to false and try to log in from the homepage, the Waltz button disappears but no log in or error message happens.
- when you load https://archive.org/account/login.php directly and press the Waltz button, the form's submit button disappears.

**Comment by lolux** [comment]
Updated site config (still getting the event handler error):

```
{
    "*://*.archive.org/*": {
        "name": "Internet Archive",
        "logout": {
            "cookies": ["PHPSESSID", "logged-in-sig", "logged-in-user"]
        },
        "login": {
            "urls": ["https://archive.org/", "https://archive.org/account/login.php"],
            "formURL": "https://archive.org/account/login.php",
            "method": "POST",
            "usernameField": "username",
            "passwordField": "password",
            "hasHiddenInputs": true,
            "check": "a:contains('log out')"
        }
    }
}
```

**Comment by jessepollak** [comment]
This is resolved, so you should be able to add internet archive back in and have it work.

**Comment by lolux** [comment]
Hmmm, unfortunately I'm still getting an event handler error: https://www.dropbox.com/s/d4upe9vsvflsx8t/Screenshot%202014-01-06%2021.44.40.jpg

(I'm pretty sure I pulled the patch correctly: https://www.dropbox.com/s/e4e19rwjgi74gxp/Screenshot%202014-01-06%2021.46.52.jpg)

**Comment by jessepollak** [comment]
Ah, I think I fixed one case, but not the other. Are you seeing this when you're on the login page or just when you're on a non-login page?

**Comment by lolux** [comment]
I'm fairly certain that I've tested it both ways in the past. Today,
however, I've only been testing the login page.

(I can run another test both ways as soon as I can figure out why GitHub is
suddenly not recognizing my public key. And here I thought git and I were
starting to become good friends. [Insert arrrrrrg here!])

**Comment by jessepollak** [comment]
OK, I think this should be fixed now. I added internet archive as well, so test with that.

**Comment by lolux** [comment]
Almost!

Waltz button works everwhere (home page, search pages, item pages) except on the actual login page: https://archive.org/account/login.php. Using it here still produces console error message: https://www.dropbox.com/s/h2svyloa3akm1vh/Screenshot%202014-01-07%2000.58.11.jpg

**Comment by lolux** [comment]
Could this have anything to do w/ the lack of an action value in the form
tag?

**Comment by jessepollak** [comment]
Hmm, it's working for me on all pages. Can you pull the latest and try again and verify that it's still failing?

**Comment by lolux** [comment]
Still getting the console error
![screen shot 2014-01-08 at 2 22 13 pm](https://f.cloud.github.com/assets/5421342/1871667/41cb843a-789a-11e3-9fee-5c57cf225d9e.jpg)
 from login attempts via this page https://archive.org/account/login.php.
When I press the Waltz button, the button disappears but nothing happens.

(Pretty sure I've pulled the latest...`git log` says I'm on commit: 21dd062576ef47fec249942f46b63ad2b2e37d84)

**Comment by jessepollak** [comment]
This confuses me, will have to keep digging.

**Comment by jessepollak** [comment]
OK, I can't figure out what's different between our setups.

When you get a chance, can you jump in #waltz on IRC (or in the Clef support room) and debug with me?

**Comment by jessepollak** [comment]
should be fixed in f3507a1
