### ISSUE TITLE
Still able to log in even though I'm logged out with Clef

### ISSUE THREAD

**Issue by apandhi** [waltzio/waltz#45]
I am still able to click the clef icon in the bottom right corner and log in even after I was automatically logged out by Waltz. 

It doesn't show the clef wave and ask me to reauth. It just logs me in right away.

**Comment by landakram** [comment]
Hey Ashish, this looks like an occurrence of a bug I've been tracking down with Clef's Android app, rather than Waltz itself. I released the latest fix for it last night -- have you updated to the latest version?

**Comment by apandhi** [comment]
No I haven't! I'll update now and let you know if I still get that error

**Comment by jessepollak** [comment]
This seems resolved, closing.
